title:            GeeksOnSecurity Website
description:      Because security matters
url:              http://www.geeksonsecurity.com
signoff:          GoS
disqus_shortname: geeksonsecurity
highlighter:      rouge
permalink:        pretty
markdown:         kramdown

links:
  - name:         Home
    url:          /
    icon:         fa-home
  - name:         Blog
    url:          /blog/
    icon:         fa-user-secret
  - name:         Javascript Deobfuscator
    url:          https://github.com/geeksonsecurity/illuminatejs
    icon:         fa-lightbulb-o
  - name:         Overlay Protector
    url:          http://overlayprotector.geeksonsecurity.com/
    icon:         fa-mobile
  - name:         Vulnerable App List
    url:          https://github.com/geeksonsecurity/vuln-web-apps
    icon:         fa-list-ol   
  - name:         IDA Tips
    url:          https://ida.geeksonsecurity.com/
    icon:         fa-question-circle
  - name:         Contact
    url:          /contact/
    icon:         fa-envelope-o


google_analytics: UA-66639465-2
