title:            GeeksOnSecurity Website
description:      Because security matters
url:              http://www.geeksonsecurity.com
signoff:          GoS
disqus_shortname: geeksonsecurity
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart

links:
  - name:         Home
    url:          /
  - name:         About
    url:          /about/
  - name:         Contact
    url:          /contact/


analytics :
  provider : google
  google :
      tracking_id : 'UA-66639465-2'
