# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GeeksOnSecurity
email: info@geeksonsecurity.com
description: Because security matters!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.geeksonsecurity.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
google_analytics: UA-66639465-2
disqus_shortname: geeksonsecurity
