title:            GeeksOnSecurity Website
description:      Because security matters
url:              http://www.geeksonsecurity.com
signoff:          GoS
disqus_shortname: geeksonsecurity
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart

links:
  - name:         Home
    url:          /
    icon:         fa-home
  - name:         Blog
    url:          /blog/
    icon:         fa-user-secret
  - name:         Contact
    url:          /contact/
    icon:         fa-envelope-o


analytics :
  provider : google
  google :
      tracking_id : 'UA-66639465-2'
